---
  output: github_document
---
  
  ```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

## R-code for '`GCalignR`: An R package for aligning Gas-Chromatography data for ecological and evolutionary studies'
#### Meinolf Ottensmann, Martin A. Stoffel, Hazel J. Nichols and Joseph I. Hoffman 

* **R_code.pdf** contains the code for all analyses. In addition, we provide our datafiles in the folder called data, which should be placed in a subfolder of the working directory in order to repeat analyses.

## **`data`**
This folder contains raw data and results of our analysis. The raw data files are listed below.

+ **bbim.txt** contains the raw chemical dataset of the bumblebee *Bombus bimaculatus* formatted for **`GCalingR`**. The orignal data source can be reached here [Dellicour & Lecocq 2013, Table_S1]( http://onlinelibrary.wiley.com/store/10.1002/jssc.201300388/asset/supinfo/jssc3437-sup-0001-TableS1.zip?v=1&s=57d5d58273d1d4207e70c72cecd5bba4b1fe95a1)

+ **bbim_ms.txt** contains an aligned subset of the raw chemical dataset of the bumblebee *Bombus bimaculatus* based on peaks that were identified by GC-MS. The orignal data source can be reached here [Dellicour & Lecocq 2013, Table_S4]( http://onlinelibrary.wiley.com/store/10.1002/jssc.201300388/asset/supinfo/jssc3437-sup-0001-TableS1.zip?v=1&s=57d5d58273d1d4207e70c72cecd5bba4b1fe95a1)

+ **beph.txt** contains the raw chemical dataset of the bumblebee *Bombus ephippiatus* formatted for **`GCalingR`**. The orignal data source can be reached here [Dellicour & Lecocq 2013, Table_S1]( http://onlinelibrary.wiley.com/store/10.1002/jssc.201300388/asset/supinfo/jssc3437-sup-0001-TableS1.zip?v=1&s=57d5d58273d1d4207e70c72cecd5bba4b1fe95a1)

+ **beph_ms.txt** contains an aligned subset of the raw chemical dataset of the bumblebee *Bombus ephippiatus* based on peaks that were identified by GC-MS. The orignal data source can be reached here [Dellicour & Lecocq 2013, Table_S4]( http://onlinelibrary.wiley.com/store/10.1002/jssc.201300388/asset/supinfo/jssc3437-sup-0001-TableS1.zip?v=1&s=57d5d58273d1d4207e70c72cecd5bba4b1fe95a1)

+ **bfla.txt** contains the raw chemical dataset of the bumblebee *Bombus flavifrons* formatted for **`GCalingR`**. The orignal data source can be reached here [Dellicour & Lecocq 2013, Table_S1]( http://onlinelibrary.wiley.com/store/10.1002/jssc.201300388/asset/supinfo/jssc3437-sup-0001-TableS1.zip?v=1&s=57d5d58273d1d4207e70c72cecd5bba4b1fe95a1)


+ **bfla_ms.txt** contains an aligned subset of the raw chemical dataset of the bumblebee *Bombus flavifrons* based on peaks that were identified by GC-MS. The orignal data source can be reached here [Dellicour & Lecocq 2013, Table_S4]( http://onlinelibrary.wiley.com/store/10.1002/jssc.201300388/asset/supinfo/jssc3437-sup-0001-TableS1.zip?v=1&s=57d5d58273d1d4207e70c72cecd5bba4b1fe95a1)

+ **earwig.txt** contains a raw chemical dataset of European earwig *Forficula auricularia* formatted for **`GCalignR`**. The original data source can be reached here [Wong et al. 2014,  	Data for DRYAD.xlsx](https://datadryad.org/resource/doi:10.5061/dryad.73180)

## **`R`**
+ Contains custom scripts that were used for some of the computations.

## Reference

[Ottensmann M, Stoffel MA, Nichols HJ, Hoffman JI (2018) GCalignR: An R package for aligning gas-chromatography data for ecological and evolutionary studies. PLoS ONE 13(6): e0198311. https://doi.org/10.1371/journal.pone.0198311](https://doi.org/10.1371/journal.pone.0198311)
